development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
#the above tells AR how to connect to the database
#this file gives AR the necessary details about how to connect to our database like which adapter we are usingbut AR supports other database adapters such as MYSQL and PostgreSQL and the name of the database